#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
#bspc config window_gap           10
bspc config window_gap           2

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Galculator state=floating

bspc config focused_border_color \#ddc7a1
bspc config normal_border_color \#1d2021


# Terminate already running polybar, picom and sxhkd instances
processes=("picom" "polybar" "sxhkd" "dunst")

for process in "${processes[@]}"; do
  if pidof -q "$process"; then
    pkill -9 -x "$process" > /dev/null; sleep 0.1
  fi
done

# Runs sxhkd (Keyboard shortcuts manager)
sxhkd &

# Runs picom (Compositor)
picom &

# Runs polybar (Taskbar)
polybar --reload &

# Run the notification service
dunst &
#/usr/lib/notify-osd/notify-osd &

# Set a random wallpaper
feh --randomize --no-fehbg --bg-fill $HOME/Pictures/Wallpapers/gruvbox/minimal &

# Set the keyboard layout to abnt2
setxkbmap -model abnt2 -layout br &

# Fix cursor
xsetroot -cursor_name left_ptr

dunstify "System reloaded"


