
[font]
normal.family = "JetBrainsMono" 
normal.style = "Regular"
size = 8

[window]
opacity = 0.95
# opacity = 1
padding.x = 5
padding.y = 5

[scrolling]
history = 1000

[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_material.toml"]
