#!/usr/bin/env bash

case $1 in
    "aliases")
        vim $HOME/.bash_aliases 
        . $HOME/.bash_aliases
    ;;
    "alacritty")
        vim $HOME/.config/alacritty/alacritty.toml
    ;;
    "bash")
        vim $HOME/.bashrc
    ;;
    "bspwm")
        vim $HOME/.config/bspwm/bspwmrc 
        bspc wm -r
    ;;
    "dunst")
        vim $HOME/.config/dunst/dunstrc
    ;;
    "picom")
        vim $HOME/.config/picom/picom.conf
    ;;
    "polybar")
        vim $HOME/.config/polybar/config.ini
    ;;
    "rofi")
        vim $HOME/.config/rofi/config.rasi
    ;;
    "starter")
        vim $HOME/.config/starter.sh
    ;;
    "sxhkd")
        vim $HOME/.config/sxhkd/sxhkdrc
	pkill -USR1 -x sxhkd
    ;;
    "vim")
        vim $HOME/.vimrc
    ;;
    "zathura")
        vim $HOME/.config/zathura/zathurarc
    ;;
    *)
        echo "Option $1 is not valid"
        exit 1
    ;;
esac
