#!/usr/bin/env bash

#━═
title=""
volume="$(pulsemixer --get-volume | cut -d ' ' -f 1)"
changed=0

if [ "$1" == "up" ]; then
    if (( $volume < 100 )); then
        wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
        option="Volume UP"
        changed=1
    fi
elif [ "$1" == "down" ]; then
    if (( $volume > 0 )); then
        wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
        option="Volume DOWN"
        changed=1
    fi
fi

if [ "$2" == "no-notification" ]; then
    exit 0
fi

if (( changed > 0 )); then
    volume="$(pulsemixer --get-volume | cut -d ' ' -f 1)"
    bar_width="$(($volume / 5))"
    bar=" "
    if (( $volume == 100 )); then
        bar="     ▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰     $volume\% "
    elif (( $volume >= 70 )); then
        echo "$((20 - $bar_width))"
        bar="     $(printf '▰%.0s' $(seq 1 $bar_width))$(printf ' %.0s' $(seq 1 $((20 - $bar_width))))      $volume\% "
    elif (( $volume >= 35 )); then
        bar="     $(printf '▰%.0s' $(seq 1 $bar_width))$(printf ' %.0s' $(seq 1 $((20 - $bar_width))))      $volume\% "
    elif (( $volume > 0 )); then
        bar="     $(printf '▰%.0s' $(seq 1 $bar_width))$(printf ' %.0s' $(seq 1 $((20 - $bar_width))))      $volume\% "
    else
        bar="                              $volume\% "
    fi
    dunstify -t 1000 --icon=display-brightness --replace=11111 "$option" "$bar" 
fi
